import React, { useState } from 'react';
import { BookOpen, AlertTriangle, GraduationCap, Calculator, Download, Printer, Layers, FileText, ChevronDown, ChevronUp, Loader2, Sparkles, CheckCircle2, ListChecks } from 'lucide-react';
import { ExamData, QA } from '../types';
import DiagramGenerator from './DiagramGenerator';
import { generateExamPdf } from '../services/pdfService';

interface ResultsSectionProps {
  data: ExamData;
  userDetails?: any;
}

const QuestionAccordionItem: React.FC<{ q: QA; index: number; forceOpen?: boolean; isPdf?: boolean }> = ({ q, index, forceOpen = false, isPdf = false }) => {
  const [isOpen, setIsOpen] = useState(false);
  const showContent = isOpen || forceOpen;

  return (
    <div className={`border-b border-slate-100 last:border-0 ${forceOpen ? 'py-6' : ''} break-inside-avoid`}>
      {!forceOpen && (
        <button
          onClick={() => setIsOpen(!isOpen)}
          className="w-full text-left p-5 flex items-start justify-between gap-4 hover:bg-slate-50 transition-colors group"
        >
          <span className="font-bold text-slate-800 text-lg group-hover:text-navy transition-colors">
            Q{index + 1}. {q.question}
          </span>
          <div className={`mt-1 text-slate-400 group-hover:text-navy transition-colors flex-shrink-0`}>
            {showContent ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
          </div>
        </button>
      )}

      {forceOpen && (
        <div className="px-2 mb-4">
          <h4 className="font-black text-black text-xl mb-3 leading-tight tracking-tight">Q{index + 1}. {q.question}</h4>
        </div>
      )}

      <div className={`${showContent ? 'block' : 'hidden'} ${forceOpen ? 'px-2' : 'px-6 pb-6'} animate-fade-in`}>
        <div className={`pl-6 border-l-[4px] ${forceOpen ? 'border-black/20' : 'border-slate-100'}`}>
          <div className={`prose max-w-none text-black whitespace-pre-line text-justify ${forceOpen ? 'text-[12pt] font-medium leading-relaxed font-serif' : 'font-medium'}`}>
            {q.answer.split('**').map((part, i) =>
              i % 2 === 1 ? <strong key={i} className="text-black font-bold">{part}</strong> : part
            )}
          </div>

          {q.diagramPrompt && showContent && (
            <div className="mt-6">
              <DiagramGenerator prompt={q.diagramPrompt} onlyCached={isPdf} />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

const QuestionCard: React.FC<{
  title: string;
  questions: QA[];
  icon: React.ReactNode;
  colorClass: string;
  bgClass: string;
  className?: string;
  forceOpen?: boolean;
  isPdf?: boolean;
}> = ({ title, questions, icon, colorClass, bgClass, className = "", forceOpen = false, isPdf = false }) => {
  if (!questions || questions.length === 0) return null;

  return (
    <div className={`bg-white rounded-2xl shadow-lg border border-slate-200 overflow-hidden mb-10 ${className} ${forceOpen ? 'shadow-none border-0 mb-8' : ''}`}>
      <div className={`${bgClass} p-6 flex items-center justify-between border-b-4 border-black/10`}>
        <div className="flex items-center gap-4">
          <div className={`${forceOpen ? 'text-black' : ''}`}>
            {icon}
          </div>
          <h2 className={`font-black text-2xl tracking-tight uppercase ${forceOpen ? 'text-black' : colorClass}`}>
            {title}
          </h2>
        </div>
        {!isPdf && (
          <span className={`${colorClass} font-black text-sm bg-white/60 px-4 py-1.5 rounded-full border border-current/20 shadow-sm`}>
            {questions.length} Items
          </span>
        )}
      </div>
      <div className="flex flex-col p-2">
        {questions.map((q, idx) => (
          <QuestionAccordionItem key={idx} q={q} index={idx} forceOpen={forceOpen} isPdf={isPdf} />
        ))}
      </div>
    </div>
  );
};

const ResultsSection: React.FC<ResultsSectionProps> = ({ data, userDetails }) => {
  const [activeTab, setActiveTab] = useState<string>('veryshort');
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const handleSavePDF = async () => {
    setIsGeneratingPdf(true);
    // Wait for any images to potentially load
    await new Promise(resolve => setTimeout(resolve, 500));
    try {
      // Pass userDetails to the generator for the cover page
      const success = await generateExamPdf(data, userDetails);
      if (!success) {
        alert("PDF generation failed. Using text fallback.");
        handleDownloadText();
      }
    } catch (error) {
      console.error("PDF Export Error:", error);
      alert("An unexpected error occurred during PDF export.");
    } finally {
      setIsGeneratingPdf(false);
    }
  };

  const handleDownloadText = () => {
    let content = `TOPIC: ${data.topicName}\n\n`;
    content += `GENERATED BY NOTE2EXAM AI\n================================\n\n`;

    const addSection = (title: string, questions: QA[]) => {
      if (questions && questions.length > 0) {
        content += `${title}\n${'-'.repeat(title.length)}\n\n`;
        questions.forEach((q, i) => {
          content += `Q${i + 1}. ${q.question}\n`;
          const cleanAnswer = q.answer.replace(/\*\*/g, '');
          content += `Answer:\n${cleanAnswer}\n`;
          if (q.diagramPrompt) {
            content += `[Visual Diagram Suggested: ${q.diagramPrompt}]\n`;
          }
          content += `\n`;
        });
        content += `\n`;
      }
    };

    addSection("VERY SHORT QUESTIONS (1-2 Marks)", data.veryShortQuestions);
    addSection("SHORT ANSWER QUESTIONS (3-5 Marks)", data.shortQuestions);
    addSection("LONG ANSWER / ESSAYS (8-16 Marks)", data.longQuestions);
    addSection("NUMERICALS & DERIVATIONS", data.numericals);

    if (data.examinerNotes && data.examinerNotes.length > 0) {
      content += `EXAMINER'S NOTES\n----------------\n`;
      data.examinerNotes.forEach(note => {
        content += `- ${note}\n`;
      });
      content += `\n`;
    }

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${data.topicName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_study_guide.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const tabs = [
    { id: 'veryshort', label: 'Very Short', count: data.veryShortQuestions.length, icon: BookOpen, color: 'text-emerald-600', activeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
    { id: 'short', label: 'Short', count: data.shortQuestions.length, icon: Layers, color: 'text-blue-600', activeClass: 'bg-blue-50 text-blue-700 border-blue-200' },
    { id: 'long', label: 'Long Answer', count: data.longQuestions.length, icon: GraduationCap, color: 'text-purple-600', activeClass: 'bg-purple-50 text-purple-700 border-purple-200' },
    { id: 'numerical', label: 'Numericals', count: data.numericals.length, icon: Calculator, color: 'text-orange-600', activeClass: 'bg-orange-50 text-orange-700 border-orange-200' },
    { id: 'notes', label: 'Notes', count: data.examinerNotes.length, icon: AlertTriangle, color: 'text-yellow-600', activeClass: 'bg-yellow-50 text-yellow-700 border-yellow-200' },
  ].filter(tab => tab.count > 0);

  React.useEffect(() => {
    if (tabs.length > 0 && !tabs.find(t => t.id === activeTab)) {
      setActiveTab(tabs[0].id);
    }
  }, [tabs, activeTab]);

  const ExaminerNotesCard = () => (
    <div className={`rounded-3xl shadow-xl border overflow-hidden mb-12 bg-yellow-50 border-yellow-200`}>
      <div className={`bg-yellow-100 text-yellow-900 p-8 flex items-center gap-5`}>
        <AlertTriangle className={`w-10 h-10 text-yellow-700`} />
        <h2 className="font-black text-3xl tracking-tight uppercase">Examiner's Expert Tips</h2>
      </div>
      <div className="p-10">
        <ul className="space-y-6">
          {data.examinerNotes.map((note, idx) => (
            <li key={idx} className={`flex items-start gap-5 font-bold text-yellow-900/80`}>
              <div className={`mt-2 w-4 h-4 rounded-full flex-shrink-0 bg-yellow-500`} />
              <span className="flex-1">{note}</span>
            </li>
          ))}
        </ul>
      </div>
    </div>
  );

  return (
    <div className="w-full max-w-4xl mx-auto pb-12">

      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-center gap-4 mb-8 animate-slide-down">
        <div className="text-left">
          <div className="flex items-center gap-2">
            <span className="bg-emerald-100 text-emerald-800 text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-widest border border-emerald-200">Analysis Done</span>
            <span className="bg-blue-100 text-blue-800 text-[10px] font-black px-2 py-0.5 rounded-full uppercase tracking-widest border border-blue-200">Gemini Pro</span>
          </div>
          <h2 className="text-3xl font-black text-slate-800 mt-2 flex items-center gap-2 tracking-tighter">
            <FileText className="text-navy" size={28} /> {data.topicName}
          </h2>
        </div>
        <div className="flex gap-3">
          <button
            onClick={handleDownloadText}
            className="flex items-center gap-2 px-5 py-3 bg-white border-2 border-slate-200 rounded-2xl text-slate-700 hover:bg-slate-50 hover:border-slate-300 transition-all shadow-sm font-black text-xs uppercase tracking-wider"
          >
            <Download size={18} />
            Text
          </button>
          <button
            onClick={handleSavePDF}
            disabled={isGeneratingPdf}
            className="flex items-center gap-2 px-6 py-3 bg-navy text-white rounded-2xl hover:bg-slate-900 transition-all shadow-xl hover:shadow-2xl font-black text-xs uppercase tracking-wider disabled:bg-slate-400 disabled:cursor-wait active:scale-95"
          >
            {isGeneratingPdf ? <Loader2 size={18} className="animate-spin" /> : <Printer size={18} />}
            {isGeneratingPdf ? 'Generating PDF...' : 'Download Master Guide'}
          </button>
        </div>
      </div>

      {/* --- TAB NAVIGATION (Screen Only) --- */}
      <div className="mb-6 overflow-x-auto pb-4 no-scrollbar animate-slide-down">
        <div className="flex space-x-3 min-w-max px-1">
          {tabs.map((tab) => {
            const isActive = activeTab === tab.id;
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`
                  flex items-center gap-2 px-5 py-3 rounded-2xl text-sm font-black transition-all duration-300 border-2
                  ${isActive
                    ? `${tab.activeClass} shadow-lg scale-105 -translate-y-1`
                    : 'bg-white text-slate-500 border-slate-100 hover:border-slate-200 hover:text-slate-700'}
                `}
              >
                <Icon size={18} className={isActive ? 'text-current' : tab.color} />
                {tab.label}
                <span className={`ml-1 text-[10px] px-2 py-0.5 rounded-full ${isActive ? 'bg-white/50' : 'bg-slate-100'}`}>
                  {tab.count}
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* --- TAB CONTENT (Screen Only) --- */}
      <div className="animate-fade-in min-h-[400px]">
        {activeTab === 'veryshort' && (
          <QuestionCard
            title="Very Short Questions (1-2 Marks)"
            questions={data.veryShortQuestions}
            icon={<BookOpen size={24} className="text-emerald-600" />}
            colorClass="text-emerald-900"
            bgClass="bg-emerald-50"
          />
        )}
        {activeTab === 'short' && (
          <QuestionCard
            title="Short Answer Questions (3-5 Marks)"
            questions={data.shortQuestions}
            icon={<Layers size={24} className="text-blue-600" />}
            colorClass="text-blue-900"
            bgClass="bg-blue-50"
          />
        )}
        {activeTab === 'long' && (
          <QuestionCard
            title="Long Answer / Essays (8-16 Marks)"
            questions={data.longQuestions}
            icon={<GraduationCap size={24} className="text-purple-600" />}
            colorClass="text-purple-900"
            bgClass="bg-purple-50"
          />
        )}
        {activeTab === 'numerical' && (
          <QuestionCard
            title="Numericals & Derivations"
            questions={data.numericals}
            icon={<Calculator size={24} className="text-orange-600" />}
            colorClass="text-orange-900"
            bgClass="bg-orange-50"
          />
        )}
        {activeTab === 'notes' && <ExaminerNotesCard />}
      </div>
    </div>
  );
};

export default ResultsSection;